FROM node:12

RUN apt-get update

EXPOSE 3001 8080
COPY ["./package.json", "./package-lock.json", ".eslintrc.js", "tsconfig.build.json", "tsconfig.json", ".env", ".env.production", "/app/"]
WORKDIR /app
RUN npm i -g nest
RUN npm install --only=production
COPY ./src /app/src

CMD npm run start