version: "3"
services:
  app:
    container_name: products_api
    restart: always
    build: .
    environment:
      - PORT=8080
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"